### ISSUE TITLE
Can you add a raider, where we can use tokens to mass ping discord channels, so if someone wanted to just ping a bunch of people and dont need a bot they can just use like alt accounts and stuff

### ISSUE THREAD

**Issue by pleasestop2** [Nyxoy201/nebula#7]
Can you add a raider, where we can use tokens to mass ping discord channels, so if someone wanted to just ping a bunch of people and dont need a bot they can just use like alt accounts and stuff

**Comment by Nyxoy201** [comment]
maybe in the new version 🙏
